In [27]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns

In [28]:
df = pd.read_csv("../data/medical_insurance_2026_kaggle.csv")
df1 = pd.read_csv("../data/health_insurance_cost_and_risk_dataset.csv")

In [29]:
df.head()

,record_date,year,quarter,age,age_group,sex,sex_female,bmi,bmi_category,children,...,region,region_northeast,region_northwest,region_southeast,region_southwest,charges,monthly_premium_est,charges_per_child,insurance_tier,bmi_age_interaction
0,2024-02-01,2024,1,19,Young Adult (18-25),female,1,27.90,Overweight,0,...,southwest,0,0,0,1,16884.92,1407.08,0.00,Platinum,530.10
1,2024-12-30,2024,4,18,Young Adult (18-25),male,0,33.77,Obese Class I,1,...,southeast,0,0,1,0,1725.55,143.80,1725.55,Bronze,607.86
2,2023-05-11,2023,2,28,Adult (26-35),male,0,33.00,Obese Class I,3,...,southeast,0,0,1,0,4449.46,370.79,1483.15,Silver,924.00
3,2024-07-18,2024,3,33,Adult (26-35),male,0,22.70,Normal Weight,0,...,northwest,0,1,0,0,21984.47,1832.04,0.00,Diamond,749.10
4,2024-02-05,2024,1,32,Adult (26-35),male,0,28.88,Overweight,0,...,northwest,0,1,0,0,3866.86,322.24,0.00,Bronze,924.16

checked for missing value and none were found. If missing value were identified they would be evaluated and depending on the variable and amount of missing data, values may be retained or dropped.

In [30]:
df.isnull().sum()

record_date            0
year                   0
quarter                0
age                    0
age_group              0
sex                    0
sex_female             0
bmi                    0
bmi_category           0
children               0
smoker                 0
smoker_flag            0
is_high_risk           0
risk_score             0
region                 0
region_northeast       0
region_northwest       0
region_southeast       0
region_southwest       0
charges                0
monthly_premium_est    0
charges_per_child      0
insurance_tier         0
bmi_age_interaction    0
dtype: int64

checked for data types and the record_date was found to have string instead of integer.

In [31]:
df.dtypes

record_date                str
year                     int64
quarter                  int64
age                      int64
age_group                  str
sex                        str
sex_female               int64
bmi                    float64
bmi_category               str
children                 int64
smoker                     str
smoker_flag              int64
is_high_risk             int64
risk_score             float64
region                     str
region_northeast         int64
region_northwest         int64
region_southeast         int64
region_southwest         int64
charges                float64
monthly_premium_est    float64
charges_per_child      float64
insurance_tier             str
bmi_age_interaction    float64
dtype: object

record_date data type was changed from string to datetime format.

In [32]:
df["record_date"]=pd.to_datetime(df["record_date"])
df.dtypes

record_date            datetime64[us]
year                            int64
quarter                         int64
age                             int64
age_group                         str
sex                               str
sex_female                      int64
bmi                           float64
bmi_category                      str
children                        int64
smoker                            str
smoker_flag                     int64
is_high_risk                    int64
risk_score                    float64
region                            str
region_northeast                int64
region_northwest                int64
region_southeast                int64
region_southwest                int64
charges                       float64
monthly_premium_est           float64
charges_per_child             float64
insurance_tier                    str
bmi_age_interaction           float64
dtype: object

Verified that there are no duplicate rows in the dataset. If any duplicate rows had been identified, they would have been be dropped.

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df1.head()

,age,sex,bmi,children,smoker,region,charges,blood_pressure,exercise_frequency,pre_existing_condition,occupation_risk,annual_income
0,19.0,female,27.900,0.0,yes,southwest,16884.92400,139.0,Never,True,high,104158.67
1,18.0,male,33.770,1.0,no,southeast,1725.55230,129.9,Weekly,True,moderate,43530.88
2,28.0,male,33.000,3.0,no,southeast,4449.46200,111.1,Rarely,False,high,113004.75
3,33.0,male,22.705,0.0,no,northwest,21984.47061,126.9,Rarely,False,high,185041.26
4,32.0,male,28.880,0.0,no,northwest,3866.85520,134.7,Rarely,True,low,46747.97

Checked for missing value. There was one missing value each in age, bmi, and children column. Since the number of missing values was minimal reltive to the dataset size, the missing values were dropped from th dataset.

In [35]:
df1.isnull().sum()

age                       1
sex                       0
bmi                       1
children                  1
smoker                    0
region                    0
charges                   0
blood_pressure            0
exercise_frequency        0
pre_existing_condition    0
occupation_risk           0
annual_income             0
dtype: int64

In [40]:
df1.dropna (subset=["age", "bmi", "children"], inplace=True)
df.isnull().sum()

record_date            0
year                   0
quarter                0
age                    0
age_group              0
sex                    0
sex_female             0
bmi                    0
bmi_category           0
children               0
smoker                 0
smoker_flag            0
is_high_risk           0
risk_score             0
region                 0
region_northeast       0
region_northwest       0
region_southeast       0
region_southwest       0
charges                0
monthly_premium_est    0
charges_per_child      0
insurance_tier         0
bmi_age_interaction    0
dtype: int64

checked for data types and age and children were found to have string and float instead of integer.

In [41]:
df1.dtypes

age                       float64
sex                           str
bmi                       float64
children                  float64
smoker                        str
region                        str
charges                   float64
blood_pressure            float64
exercise_frequency            str
pre_existing_condition       bool
occupation_risk               str
annual_income             float64
dtype: object

The data types for age and children were changed to integer.

In [42]:
df1 = df1.astype({"age": "int", "children": "int"})
df1.dtypes

age                         int64
sex                           str
bmi                       float64
children                    int64
smoker                        str
region                        str
charges                   float64
blood_pressure            float64
exercise_frequency            str
pre_existing_condition       bool
occupation_risk               str
annual_income             float64
dtype: object

In [46]:
df1.duplicated().sum()

np.int64(0)